CREATE DATABASE coursework;

USE coursework;

CREATE TABLE users(
UserID INT PRIMARY KEY AUTO_INCREMENT,
username VARCHAR(50) NOT NULL,
email VARCHAR(50) NOT NULL,
Address VARCHAR(50) NOT NULL,
Pasword VARCHAR(255) NOT NULL
);

CREATE TABLE admin(
UserID INT PRIMARY KEY AUTO_INCREMENT,
username VARCHAR(50) NOT NULL,
email VARCHAR(50) NOT NULL,
pasword VARCHAR(255) NOT NULL);